debug: true
management:
  endpoints:
    web:
      exposure:
        exclude: "*"

logging:
  level:
    io.hpp.concertreservation : debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.internal: trace

spring:
  application:
    name: concert-reservation

server:
  port: 8500

---
spring:
  profiles:
    group:
      local: local_profile
      dev: dev_profile
      cbt: cbt_profile
      prod: prod_profile
default:
  string: default property






