debug: true
management:
  endpoints:
    web:
      exposure:
        exclude: "*"

logging:
  level:
    io.hpp.concertreservation : debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.internal: trace

spring:
  config:
    activate:
      on-profile: common
  application:
    name: concert-reservation
server:
  port: 8500

---
spring:
  profiles:
    group:
      dev: dev_profile
      test: test_profile
      prod: prod_profile
default:
  string: default property






